
work_dir: ./work_dir/ntu120/xsub/joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/NTU120_CSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64 
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: ./data/ntu120/NTU120_CSub.npz
  split: test
  window_size: 64 
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False
# model
model: model.gcn_devLSTM.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 3    
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  labeling_mode: None
  choose_model: LSTM
  hidden_size: [10,10,10,10,10,10,10,10,10]
  kernel_size: [2,2,2,2,3,2,2,3,2]
  stride: [1,1,1,1,2,1,1,2,1]
  dilation: [[1,2],[1,2],[1,2],[1,2],[1,2],[1,2],[1,2],[1,2],[1,2]]
# optim
weight_decay: 0.0003
base_lr: 0.02
step: [35, 55]
warm_up_epoch: 5

# training
num_epoch: 65
device: [0]
batch_size: 16
forward_batch_size: 16
test_batch_size: 16
nesterov: True
